### PR TITLE
Renamed Intro to Bio on Sign up and enabled user to edit Skills to Help and Skills to Improve.

### PR DESCRIPTION
**Pull request by NicBonetto**
Fixes #\<issue number\>.

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue above.

Note that we are unlikely to accept pull requests that add features without prior discussion. The best way to propose a feature is to open an issue first and discuss your ideas there before implementing them.

Always follow the [contribution guidelines](https://github.com/codebuddies/codebuddies/blob/master/contributing.md) when submitting a pull request.

Fix for issue #985

### CODE REVIEW

**Comment by lpatmo** [comment]
Thanks @NicBonetto, this is a great start!

Two issues:
1) The skills I have/skills I want to improve data does not currently display in the textarea values on the profile page: 
image

I noticed that in your profile-edit.html, you refer to {{ profile.skillsToHelp }}, but you may actually want `profile.skillHelpOthersWith` and`profile. skillWantToImprove`. Btw, you can double check what the schema looks like by typing control-m. 

2) When I edit the profile's skills textareas and try to save, the new data does not get saved, which means the data isn't getting passed to the `updateBasicInformation` in the call to the server side. Let me know if you need help figuring this out. 

3) Let me know if you'd like me to file this as a new Github issue, since I didn't discuss it in the original issue -- but it would be great if we could display the skills directly on a user's profile page too. Right now it's hidden until they click to edit their profile.

**Comment by NicBonetto** [comment]
@lpatmo thank you for the feedback. No need to file another issue, I can add it to this PR.

**Comment by NicBonetto** [comment]
@lpatmo  Sorry, I pushed a commit but I know it wasn't ready for another review yet. I have a busy sprint at work and haven't been able to work on this since the last time I pushed.

**Comment by lpatmo** [comment]
@NicBonetto Oh, I shouldn't have assumed that was your was final commit, heh, sorry. For what it's worth, I believe the `git diff` will work. Might be easier if you could push it up, since I'm not sure how to push to a forked repo, so when you could get a chance to apply it and review it at some point (no rush), please do! Thanks!

**Comment by lpatmo** [comment]
@NicBonetto If you have any time this weekend to push up the diff, let me know! Otherwise I will make the change. Thanks! We're close to a release now. :)

**Comment by lpatmo** [comment]
Made the changes in the diff block above in preparation for the Halloween release tomorrow. Thanks for getting this started, @NicBonetto!

**Pull request merged**
