### PR TITLE
Call slack invite api to invite new user to join CodeBuddies workspace

### LINKED ISSUE #972: Slack API: Send auto-email invite to user to codebuddies.slack.com when new user registers for the first time
Instead of asking users to sign up for the Slack and for the website separately, we should send an auto-invite to the user's email to codebuddies.slack.com as soon as they log in for the first time on codebuddies.org. 

Note:
- if a user chooses to log in via another Slack account, we'll still have their email when they sign up, and we should send an invite to that email.
- if a user chooses to log in via Github, we'll have that email instead for invite-sending.

### PR DESCRIPTION
**Pull request by railsstudent**
Fixes #972 

Send slack invitation to new users' email address  when they log in via github or slack.

I created a new slack workspace and issued a legacy token from it. Then, I updated "slackAppToken" in settings-development.json configuration file.

When user logs in using my github account, slack sends invite email to his/her gmail account.  User can click Join Now button to join the new workspace.

slack-invite

### CODE REVIEW

**Comment by lpatmo** [comment]
Thank you Connie!

Question: after you created the new workspace, did you create the legacy token on https://api.slack.com/custom-integrations/legacy-tokens? When I generated one there, I saw an `xoxo-` token, not one that looked like it would fit for `slackAppToken`. 

The code looks great, but I wasn't able to get an invite using the slackAppToken in CB's production for some reason, so I am trying by creating the workspace.

**Comment by lpatmo** [comment]
Update: it worked just now, for the new workspace! But the `xoxo-` token was in the `slackAppToken` spot. I wonder if this change needs to be made: 

```
-    const SLACK_TOKEN = Meteor.settings.slackAppToken;
+    const SLACK_TOKEN = Meteor.settings.slackOauthToken;
```

**Comment by railsstudent** [comment]
@lpatmo Update the code to Meteor.settings.slackOauthToken

**Comment by lpatmo** [comment]
@railsstudent Thank you! Looks great; I will merge now.

**Pull request merged**
