### PR TITLE
Issue 948 default email settings

### LINKED ISSUE #948: Default email notification settings
- An easy way for study group owners to send out an announcement to the group right now is to start a new discussion within the study group
- Members will only get those notifications if they have setting checked in their Email Notification Settings
- Proposal: set the following as default:

image
- We need to make sure to add a link to this Settings page on the footer of each email notification, next to the "unsubscribe" link that's already there

### PR DESCRIPTION
**Pull request by railsstudent**
Fixes #948 

Default all email preferences to checked when new user logged in via Slack or Github.
When users receive email, they can click unsubscribe link to open unsubscribe emails page in  a new tab.   They can uncheck email preferences that they want to retain and click Confirm button to confirm the changes.

Always follow the [contribution guidelines](https://github.com/codebuddies/codebuddies/blob/master/contributing.md) when submitting a pull request.

### CODE REVIEW

**Comment by railsstudent** [comment]
I committed new API key of sparkpost to development-settings.json file. Please let me know if it is bad practice or not.

**Comment by railsstudent** [comment]
unsubscribe_email_preferences
confirm_email_unsubscription
updated_email_settings
unsubscribe_disucssion_response
discussion_response_unsubscribed

**Comment by lpatmo** [comment]
Thank you Connie!! I will take a closer look tomorrow night.

**Comment by railsstudent** [comment]
@lpatmo In this comment, https://github.com/codebuddies/codebuddies/issues/948#issuecomment-425824551, @distalx  suggested to render email preferences in unsubscribe link and users can update preferences. 
Please confirm which approach to use. thanks.

**Comment by railsstudent** [comment]
Yes,  unsubscribe_from_mailing_list.html renders the content of http://localhost:3000/unsubscribe/jASAFNH6fHrFzRpaQ.

**Comment by distalx** [comment]
Made minor improvement into workflow so to update changes user don't have to be logged-in.

**Pull request merged**
