### PR TITLE
Home css variable fix

### PR DESCRIPTION
**Pull request by MattKomorcec**
Replace hardcoded value of #fff with a variable $white in _home.scss file.

### CODE REVIEW

**Comment by stain88** [comment]
Seems to be a lot more going on in this PR than just a variable change. Why so many files touched?

**Comment by stain88** [comment]
I believe you want to be branching from `staging`, rather than `master`, but pinging @lpatmo @distalx (@railsstudent ) to confirm

**Comment by distalx** [comment]
Yes, please take a pull from the staging on your current branch and then push that changes back here. 
Thanks 

-----Original Message-----

**Comment by MattKomorcec** [comment]
This is such a mess, I'll create a new pull request, that seems like a faster option :-)

**Pull request closed without merging**
