### PR TITLE
Enable docker containers for PR's

### PR DESCRIPTION
**Pull request by nalbina**
This will effectively tag pull requests on commit using docker-hub.
I have added a dummy `docker-compose.test.yml` in order to trigger the `post_test` hook.
What this will do is push a docker container to `codebuddiesdotorg/codebuddies:PR_$PRNUMBER` which we can then take from there for demo purposes.

### CODE REVIEW

**Comment by nalbina** [comment]
Let's wait till docker-hub creates a `codebuddiesdotorg/codebuddies:PR_827` ;)

**Comment by nalbina** [comment]
Worth noting is that we hook into the post_test, because we won't get a build or push event for external pull requests (e.g forks)

**Comment by nalbina** [comment]
It works, waiting for your review @distalx @lpatmo

**Comment by distalx** [comment]
Looks good to me.

-----Original Message-----

**Pull request merged**
