### PR TITLE
CSS Fix: Today i learn ui now supports newline character

### PR DESCRIPTION
**Pull request by gauravchl**
Old 👇
screen shot 2018-11-10 at 12 39 00 pm

New 👇
screen shot 2018-11-10 at 1 02 25 pm

### CODE REVIEW

**Comment by lpatmo** [comment]
Thanks @gauravchl :)

**Comment by lpatmo** [comment]
@gauravchl Gah, I'm sorry, I clicked too quickly! Could you create a PR against the `staging` branch? That should be the branch to merge into, not `master`.

**Comment by gauravchl** [comment]
@lpatmo My bad, creating another PR...

**Comment by gauravchl** [comment]
@lpatmo Here it is: https://github.com/codebuddies/codebuddies/pull/1074

**Pull request merged**
