### PR TITLE
Issue: 964 - Star (or highlight) active groups on the /studygroups page 

### LINKED ISSUE #964: Star (or highlight) active groups on the /studygroups page
Thanks to @clockwerkz for this idea:

Clicking through the groups, it's hard to figure out which ones are active unless you click through and look through progress logs or past hangouts. 

Would be helpful to highlight the active ones.

### PR DESCRIPTION
**Pull request by mahamshahid18**
Fixes #964 .

* Added `Last Activity` text on study group cards (when `updatedAt` field is present)
* Added logic for updating the activity (`updatedAt` field) for study groups
* Added a helper function for returning last activity time

### CODE REVIEW

**Comment by lpatmo** [comment]
Thank you @mahamshahid18! At first glance the commits look good, but I am traveling right now, using an older laptop, and just had to upgrade to macOS Mojave on it so er... the app isn't running entirely right on my machine right now, and I haven't gotten a chance to review this PR more closely. 

In the meantime, as an aside: would you be interested in opening up a new PR to get recognition as a contributor? (See: https://docs.codebuddies.org/code-contribution/recognition)

**Comment by mahamshahid18** [comment]
That's fine, take your time @lpatmo :)

And yes, I'll do that in the meanwhile 👍

**Comment by distalx** [comment]
Hey @mahamshahid18, thanks a lot for taking the time to send a pull request. Here are some suggestions I hope you'll find helpful. If you are busy no problem, I can fix it up for you and merge it.

I noticed that we are updating `updatedAt` timestamp for the following events.
 - update study group info
 - create new study group
 - update study group title

we should also cover couple of other events and update the `updatedAt` field for following events too.
- when someone Joins study group [here](https://github.com/codebuddies/codebuddies/blob/11b75ca7e2b8df33c7061edb017fe17ee2f07063/server/study_groups/methods.js#L103)
- when someone creates new hangout [here](https://github.com/codebuddies/codebuddies/blob/11b75ca7e2b8df33c7061edb017fe17ee2f07063/server/hangouts/helpers.js#L101)
- when someone creates new discussion [here](https://github.com/codebuddies/codebuddies/blob/11b75ca7e2b8df33c7061edb017fe17ee2f07063/server/discussions/methods.js#L72)

For date-time parsing we are using the [moment.js](https://momentjs.com/), So in favour of momentjs we can remove [getUpdatedAtTime](https://github.com/codebuddies/codebuddies/pull/1010/files#diff-9a19db5b8bb5bdefc62c2197508ff666R65) helper and reduce the technical debt. 

To use moment js in to our templating we can create a global helper function like [this](https://github.com/codebuddies/codebuddies/blob/11b75ca7e2b8df33c7061edb017fe17ee2f07063/client/templates/main.js#L31) 

very roughly 

```
// main.js
Template.registerHelper("relativeTime", function(date) {
  return moment(date).startOf('minute').fromNow();
});

//some_file.html
{{relativeTime updatedAt}}
```

Thanks again.

**Comment by mahamshahid18** [comment]
Hey @distalx thank you for the specific instructions. It really helped get stuff done quickly, much appreciated :)

I've added the changes that you requested. Please take a look and let me know if anything else needs to be improved :)

**Comment by lpatmo** [comment]
Thank you @mahamshahid18 and @distalx! Merging this in now!

**Pull request merged**
