### PR TITLE
Updated SweetAlert2 with meteor compatible sweetAlert2

### LINKED ISSUE #1034: Make existing `swal` code compatible with sweetalert 2 package
See: https://github.com/codebuddies/codebuddies/pull/1025#issuecomment-431624545

@thunatos has started working on this.

### PR DESCRIPTION
**Pull request by thunatos**
Fixes #1034 

Updated all swal(s) to properly work with the new sweetAlert2 package.

### CODE REVIEW

**Comment by lpatmo** [comment]
The way to trigger that sweetAlert is to log out, then click on a button (like "create a hangout"). Then you should see this:

image

**Comment by thunatos** [comment]
Ok I will work on this and have it done soon. Yes, if we can submit under another PR that would be beneficial. :-) 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by thunatos** [comment]
The issue has been fully completed, just need a new PR so that I can switch over to that branch. Once that occurs I will push my changes and we can enjoy some sweet, sweet alerts ;) :tada:

**Comment by lpatmo** [comment]
@thunatos Thanks for the poke (and apologizies -- the last two days have been a bit crazy busy!). By "file a new PR" do you mean that I should merge in https://github.com/codebuddies/codebuddies/pull/1025? Just checking! Or do you want me to file a new issue?

**Comment by thunatos** [comment]
>@thunatos Thanks for the poke (and apologizies -- the last two days have been a bit crazy busy!). By "file a new PR" do you mean that I should merge in https://github.com/codebuddies/codebuddies/pull/1025? Just checking! Or do you want me to file a new issue?

@lpatmo whatever works best, if we merge into 1025 I can do that as well! 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lpatmo** [comment]
@thunatos I've just merged in #1025! I will merge this PR next.

And I've field a new issue for the new PR: https://github.com/codebuddies/codebuddies/issues/1042

Let me know if this works! And I will add you as a collaborator also, so that your name shows up for Github assignees on issues.

**Comment by thunatos** [comment]
What that shouldn’t of happened at all. I was trying to remove them from being updated because that code was already pushed. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request merged**
