### PR TITLE
Issue 907 fontawesome upgrade

### LINKED ISSUE #907: Upgrading to FontAwesome v5 from v4
Let's explore how (or if we can easily) upgrade to FontAwesome v5, which gives us more icons like a `Patreon` icon.

### PR DESCRIPTION
**Pull request by railsstudent**
Fixes #907 

Replace fontawesome from v4 to v5.

@lpatmo @distalx  fa-sign-out, fa-trash-o, fa-pencil-square-o are replaced with fa-sign-out-alt, fa-trash-alt and fa-edit respectively in v5.  These icons are saved in "activities" and "notifications" collections in MongoDB.  
Please advise whether data patching is required. Otherwise, the icons are broken in study group activities tab and notification page.

### CODE REVIEW

**Comment by distalx** [comment]
@railsstudent , Thanks a lot for putting that together ! 
For remaining icons, we could write a migration script.

**Comment by railsstudent** [comment]
Will figure out the update query to update the icon field in the collections later this week.

**Comment by railsstudent** [comment]
@distalx  Add migration script "update-activities-notifications-icon.js" that patches fontawesome v4 icons to v5. 
The script is auto-run when the file is imported in register-api.js

**Comment by distalx** [comment]
@railsstudent , great work as always. 🚀
@lpatmo  In fontawesome 5 they have introduced following new prefixes `fab`, `fas`, `far` & `fal`. [More Info](https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4#changes)

`far` & `fal` are only available under fontawesome's [PRO license](https://fontawesome.com/pro) & We have used `far` prefix several times like [here](https://github.com/codebuddies/codebuddies/pull/917/files#diff-b49c98580726c9aef13fff2fa11b032cR18) 

It is suggested over [here](https://fontawesome.com/support#use-opensource), to use Font Awesome 5 Free for open source project.

So maybe we might want to find a replacement for those icons, or else we have to buy a pro license.

**Comment by lpatmo** [comment]
Looks like the pro license starts at $60 for 1-5 seats. I think that means 1-5 developers can commit/use the icons. Is that enough?

**Comment by distalx** [comment]
I believe we can find replacement for most icons.

**Comment by wuworkshop** [comment]
Not sure if this should be a new issue or not. With regards to replacing some of those `far` icons, perhaps these open source icons could work?
1. https://feathericons.com/

For popular brands, I got this one in my GitHub ⭐️ s:
1. https://simpleicons.org/

**Comment by sergeant-q** [comment]
I can't see justifying paying for icons where there's obviously plenty of free and open-source icon projects.

**Comment by lpatmo** [comment]
Even if we pay for FontAwesome 5.0, we *can't* use it for an open sourced project, according to their FAQ. :P 

I'll take a closer look at this PR tonight and merge it in.

**Comment by lpatmo** [comment]
(I am going to open up a new PR for the icons cleanup.)

**Comment by lpatmo** [comment]
Wait, I actually don't see any broken icons in notifications or on the activities tab in the study group. @railsstudent Is that right?

**Pull request merged**
