### PR TITLE
Allow user to edit first and last name

### LINKED ISSUE #968: Allow users to change first and last name
Feature request

What is the current behavior?
Users cannot change first and last name.

What is the expected behavior?
Users should be able to change first and last name

### PR DESCRIPTION
**Pull request by brylie**
Fixes #968

Allow users to change first and last name. They may have made a typo, or decide to change their anonymity preference for any reason.

### CODE REVIEW

**Comment by brylie** [comment]
cc: @konker

**Comment by brylie** [comment]
I can work on this later this week at the earliest.

**Comment by lpatmo** [comment]
@brylie Thank you!

**Comment by lpatmo** [comment]
Perfect now. Thank you so much, @brylie!

**Pull request merged**
