### PR TITLE
fix(design): Hide wrong participant msg till its fixed

### LINKED ISSUE #971: Hide the "24 people in 24/7 hangout" message on codebuddies.org/coworking
Until we can figure out why the wrong count is showing up underneath the Jitsi hangout frame, an easy "fix" would be to hide that particular message using CSS on https://codebuddies.org/silent. 

NOTE: Please only hide the message for the codebuddies.org/silent, not for any other pages. This means a CSS fix is required.

Getting started:
1) Check out https://docs.codebuddies.org
2) Reply to this thread to claim this issue, and let us know if you have questions! :)

### PR DESCRIPTION
**Pull request by AjayPoshak**
Fixes #971

### CODE REVIEW

**Comment by AjayPoshak** [comment]
No issues, I'll do that.

**Comment by lpatmo** [comment]
Thanks @AjayPoshak!

**Comment by sebbel** [comment]
Hey @AjayPoshak, do you need help with the issue? :)

**Comment by AjayPoshak** [comment]
@sebbel @lpatmo Apologies for the delay. I have fixed, please review it.

**Comment by lpatmo** [comment]
@AjayPoshak That works! I guess less cringy than a CSS hack. :) Thanks for your update.

**Pull request merged**
