### PR TITLE
First version of automatic sending of welcome message to new users. 

### LINKED ISSUE #775: Auto-Email Slack Welcome Message on Signup by New Members
Craft code for generating & emailing a custom **_Slack Welcome_** on new user Sign-up.

- [ ] The body of the email will be  a variant of the [attached Welcome message](https://slack-files.com/T04AQ6GEY-F8X5U3HRV-d0892dda60) that is currently in use in the Slack _#start_here_ channel.
- [ ] The email will be triggered on on of the following:
        -  new user signup via the codebuddies.org website, 
        -  personal invite, 
        -  Slack app signup
       -  direct add by an admin or moderator.
- [ ] The email will be sent to the email address provided by the new member when they fill out the Slack new user account info.  Changes to the original address won't trigger a new email.

__________________________________________________________________

A couple of edits will be needed for the text of the email:

-  The **[CHANNELS]** link currently in the doc will need to be replaced with the external link to the Slack Help Doc on browsing channels:  https://get.slack.help/hc/en-us/articles/205239967-Browse-and-join-channels

-  The **[CodeBuddies Slack Etiquette for General Members]** link currently in the doc will need to be replaced with this external link (https://slack-files.com/T04AQ6GEY-F8VRAGD0S-ebfb2269d1) - and ultimately, with a link to a (yet to be done) page on the codebuddies.org website.

### PR DESCRIPTION
**Pull request by joelmheim**
Have not completed the design of the email yet. Links are not included.
Also have not been able to test fully on my local machine due to SMTP errors.

Fixes #775.

Hoping to have a discussion with @lpatmo and others before we merge this in to determine what needs to change and have some help to fully test the functionality and design the email properly.

### CODE REVIEW

**Comment by lpatmo** [comment]
Thanks @joelmheim! Have not looked closely yet, but out of curiosity, what SMTP errors are you getting? If you DM me @linda on Slack, I can also send you a private Sparkpost key if you need it.

**Comment by railsstudent** [comment]
@lpatmo Maybe he does not have sparkpost api key.

**Comment by railsstudent** [comment]
@joelmheim Have you joinned codebuddies slack channel?

**Comment by joelmheim** [comment]
Yes

**Comment by lpatmo** [comment]
@joelmheim The template looks excellent! :) I see that the welcome template follows what's in codebuddies.org/welcome, so that is perfect. I see a couple of text changes that could be made, but I will file a separate issue about it. Thanks so much!

PS if you haven't already and would like recognition as a contributor, feel free to submit another PR re: instructions at https://docs.codebuddies.org/code-contribution/recognition.

**Pull request merged**
