### PR TITLE
CSS adjustments for hangout card (#1009)

### PR DESCRIPTION
**Pull request by mendaomn**
Hi,

As per #1009 

1. the title doesn't seem to collapse with the "i" icon! 
2. expanded and centered the RSVP button 
3. removed the JOIN NOW button, it's commented as of now. Waiting confirmation that's the right button to remove

Please let me know how I can improve this

### CODE REVIEW

**Comment by sebbel** [comment]
Hey @mendaomn thanks for your PR.
I've deployed your changes to https://codebuddies-1018.now.sh/ for easier review and created some test hangouts.
Really like the modern look you gave those hangouts! :heart:

**Comment by mendaomn** [comment]
> @sebbel Wish login could be figured out, but even without it that's a brilliant way to preview PRs! Thank you! :)
> 
> @mendaomn Yes, that is the correct button to comment out. Your code changes look good! Only issue I noticed: when the hangout title is three lines long (see the first card on https://codebuddies-1018.now.sh/hangouts), the content of the card shifts/moves. Let me know if you don't see an easy fix for that. Thanks.

I tried to work around that for a while, still haven't come up with a solution but it shouldn't be too hard to pin point to its cause. I'll dig deeper!

**Comment by mendaomn** [comment]
> @sebbel Wish login could be figured out, but even without it that's a brilliant way to preview PRs! Thank you! :)
> 
> @mendaomn Yes, that is the correct button to comment out. Your code changes look good! Only issue I noticed: when the hangout title is three lines long (see the first card on https://codebuddies-1018.now.sh/hangouts), the content of the card shifts/moves. Let me know if you don't see an easy fix for that. Thanks.

I tried to work around that for a while, still haven't come up with a solution but it shouldn't be too hard to pin point to its cause. I'll dig deeper!

**Comment by mendaomn** [comment]
> Let me know if you don't see an easy fix for that. Thanks.

I tried to work around that for a while, still haven't come up with a solution but it shouldn't be too hard to pin point to its cause. I'll dig deeper!

**Comment by lpatmo** [comment]
@mendaomn My guess is has something to do with the flex property, but perhaps one workaround could be to remove the "Scheduled by [username] with # RSVPed" from all the hangouts that are upcoming. 

I tested this out on the browser and it looks okay; let me know if this makes sense to you too!

**Comment by mendaomn** [comment]
Sounds good to me!

**Comment by lpatmo** [comment]
Hi @mendaomn! Any chance you'd be able to make a commit removing the "Scheduled by [username] with # RSVPed" this weekend? Otherwise, no worries, I will make the change. Thanks for your time!

**Comment by lpatmo** [comment]
(Actually, going to go ahead and merge this in. Will file a new Github issue for the edge case, which you are free to work on if you comment on it. Thanks!)

**Pull request merged**
