### PR TITLE
Issue 1042

### LINKED ISSUE #1014: Upgrade sweetalert 1.x to sweetalert 2.x
I am filing this bug after discussion in https://github.com/codebuddies/codebuddies/issues/821 (adding a "sign in using Github" link on the sweetalert) surfaced the fact that we need to upgrade to sweetalert 2.x before we can support having both a Github and Slack sign-in actions on the sweetalert.

The task:
- upgrade to sweetalert 2.x from 1.x
- Guidelines to follow: https://sweetalert.js.org/guides/#upgrading-from-1x

### PR DESCRIPTION
**Pull request by thunatos**
Fixes #1014 

sweetAlert 1x migration to sweetAlert2 broke API fixes. This pull request fixes all issues and allows now full integration.

### CODE REVIEW

**Comment by thunatos** [comment]
Ok @lpatmo all done!

**Comment by lpatmo** [comment]
@thunatos Thank you! I am finally back home now, and won't be traveling again for a while. I merged in #1035 just now, which caused some conflicts for this PR; am looking into that now. Two things I noticed:

- Could you reset settings-development.json back to the defaults?
- I noticed that https://localhost:3000/hangouts with this branch checked out wouldn't load. I didn't see anything obvious in the diff that would cause the problem, but wonder if you know what is causing the issue.

Thanks again!

**Comment by lpatmo** [comment]
Also: it looked like ```client/templates/status/update-status.js
client/templates/study_groups/study_group_settings.js``` were deleted. Can you explain why?

**Comment by thunatos** [comment]
Hi, I have the files restored, and reset settings on meteor, It appears that in my effort to remove the file being updated, I made the mistake of "git rm file" instead of just stashing the commit. Sorry, it was my fault on a command.

**Comment by thunatos** [comment]
@lpatmo I fixed everything, apologies for the issue... (no pun intended)

**Comment by lpatmo** [comment]
Thank you! I see one remaining issue:

- when I log in using Slack associated with an admin user account, I see this:

image

And this is what's on the server-side logs: 
```
I20181027-10:26:58.338(-7)? { Error: Invalid login: 535 5.7.8 Sorry.
I20181027-10:26:58.338(-7)?     at SMTPConnection._formatError (/Users/lindapeng/.meteor/packages/email/.1.2.3.1jwqu6j++os+web.browser+web.cordova/npm/node_modules/node4mailer/lib/smtp-connection/index.js:558:19)
I20181027-10:26:58.339(-7)?     at SMTPConnection._actionAUTHComplete (/Users/lindapeng/.meteor/packages/email/.1.2.3.1jwqu6j++os+web.browser+web.cordova/npm/node_modules/node4mailer/lib/smtp-connection/index.js:1254:34)
I20181027-10:26:58.339(-7)?     at SMTPConnection._responseActions.push.str (/Users/lindapeng/.meteor/packages/email/.1.2.3.1jwqu6j++os+web.browser+web.cordova/npm/node_modules/node4mailer/lib/smtp-connection/index.js:341:26)
I20181027-10:26:58.339(-7)?     at SMTPConnection._processResponse (/Users/lindapeng/.meteor/packages/email/.1.2.3.1jwqu6j++os+web.browser+web.cordova/npm/node_modules/node4mailer/lib/smtp-connection/index.js:707:20)
I20181027-10:26:58.339(-7)?     at SMTPConnection._onData (/Users/lindapeng/.meteor/packages/email/.1.2.3.1jwqu6j++os+web.browser+web.cordova/npm/node_modules/node4mailer/lib/smtp-connection/index.js:510:14)
I20181027-10:26:58.339(-7)?     at TLSSocket._socket.on.chunk (/Users/lindapeng/.meteor/packages/email/.1.2.3.1jwqu6j++os+web.browser+web.cordova/npm/node_modules/node4mailer/lib/smtp-connection/index.js:658:51)
I20181027-10:26:58.340(-7)?     at emitOne (events.js:116:13)
I20181027-10:26:58.340(-7)?     at TLSSocket.emit (events.js:211:7)
I20181027-10:26:58.340(-7)?     at addChunk (_stream_readable.js:263:12)
I20181027-10:26:58.340(-7)?     at readableAddChunk (_stream_readable.js:250:11)
I20181027-10:26:58.340(-7)?     at TLSSocket.Readable.push (_stream_readable.js:208:10)
I20181027-10:26:58.340(-7)?     at TLSWrap.onread (net.js:597:20)
I20181027-10:26:58.341(-7)?   code: 'EAUTH',
I20181027-10:26:58.341(-7)?   response: '535 5.7.8 Sorry.',
I20181027-10:26:58.341(-7)?   responseCode: 535,
I20181027-10:26:58.341(-7)?   command: 'AUTH PLAIN' }```

Not quite sure why this is happening; will dig.

**Comment by lpatmo** [comment]
I'm curious if you're able to recreate the same issue I see re: logging in w/ Slack and seeing "admin" as the user.

**Comment by distalx** [comment]
@thunatos thanks a lot for taking the time to send a pull request. Here are some suggestions I hope you'll find helpful.

- we have several sweetalert package installed at this point. which one are we planning on using it? 
atmospherejs - `patrickml:swal`, `cleandersonlobo:sweetalert2`
npm - `sweetalert2`

- there are some breaking changes listed [here](https://sweetalert.js.org/guides/#upgrading-from-1x), But apparently it hasn't effected us, we can still use  `title` instead of `text`. [here](https://github.com/codebuddies/codebuddies/pull/1043/files#diff-c9f69c00349e23728b7493589214494dR8), we can still use `type` and `imageUrl` So I guess both atmospherejs packages are being loaded here. 

Therefore 1) we should remove the `patrickml:swal` & npm package,  and we should also update the options's fields as mentioned [here](https://sweetalert.js.org/guides/#upgrading-from-1x).

@lpatmo, I believe that error is related to SMTP. it's not related to sweetalert.!

**Comment by thunatos** [comment]
After further review, looks like there are still a lot of changes to be made for the new integration. I will push my new changes (with everything working) and remove the packages as you mentioned before. However, I think there are some more things to discuss. I can transfer the t`title: ` into `text: ` but also, I wanted to mention some things about design. 

Inside of study_group_settings.js we have `return Bert.alert("Study Group Archived", "success", "growl-top-right");` however, there is no swal for it. I find the design to be a little nicer if we do include a swal in each one. If you do archive a group, the bert alert, and swal show... Do we want to have this design, or would it be more preferable to keep just the bert alert?

**Comment by lpatmo** [comment]
```> Inside of study_group_settings.js we have return Bert.alert("Study Group Archived", "success", "growl-top-right"); however, there is no swal for it. I find the design to be a little nicer if we do include a swal in each one. If you do archive a group, the bert alert, and swal show... Do we want to have this design, or would it be more preferable to keep just the bert alert?```

Fine to have a swal alert show after a user clicks "yes" on the "Are you sure you want to archive group?" alert.

**Comment by lpatmo** [comment]
I notice there are a few merge conflicts in `client/templates/status/learning-item.js
client/templates/study_groups/study_group_settings.js` now... let me know if you need help resolving those!

**Comment by thunatos** [comment]
> I notice there are a few merge conflicts in `client/templates/status/learning-item.js client/templates/study_groups/study_group_settings.js` now... let me know if you need help resolving those!

Fixed.

**Comment by lpatmo** [comment]
@thunatos LGTM. :) Thank you!!

**Comment by lpatmo** [comment]
... and that's a successful build! Yay!

**Pull request merged**
